### PR TITLE
oomparser: update to use kmsg based parser

### LINKED ISSUE #645: Journalctl should be runnable from inside the Docker container
Trying to run cadvisor on mac using boot2docker. mentioned issues is found while identifying docker logs cadvisor

### LINKED ISSUE #1484: Can't collect OOM events
Hello,

I'm trying to use cAdvisor to catch OOM events but I failed (probably I'm doing something wrong).
Here's my setup:

```
lsb_release -a
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 16.04 LTS
Release:    16.04
Codename:   xenial
```

```
docker version
Client:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64

Server:
 Version:      1.12.0
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   8eab29e
 Built:        Thu Jul 28 22:11:10 2016
 OS/Arch:      linux/amd64
```

And I'm running cAdvisor as follows:

```
docker run -it --volume=/:/rootfs:ro --volume=/var/run:/var/run:rw --volume=/sys:/sys:ro --volume=/var/lib/docker/:/var/lib/docker:ro --volume=/var/log:/var/log:ro --publish=8888:8080 google/cadvisor:latest -disable_metrics disk -logtostderr
I0928 14:02:52.419328       1 storagedriver.go:50] Caching stats in memory for 2m0s
I0928 14:02:52.421050       1 manager.go:140] cAdvisor running in container: "/docker/8220f6518546f643bbaf2e22d6ce1438d8fcd85c11e556504c5047b196fd040c"
W0928 14:02:52.478840       1 manager.go:148] unable to connect to Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
I0928 14:02:52.529191       1 fs.go:116] Filesystem partitions: map[/dev/sda1:{mountpoint:/var/lib/docker/overlay major:8 minor:1 fsType:ext4 blockSize:0}]
I0928 14:02:52.537331       1 manager.go:195] Machine: {NumCores:2 CpuFrequency:2599998 MemoryCapacity:13656510464 MachineID:af03dcd1dca6264136598dbff549c369 SystemUUID:AF03DCD1-DCA6-2641-3659-8DBFF549C369 BootID:0861dcdb-cfe0-43a2-bfee-1705cda0227d Filesystems:[{Device:overlay Capacity:31158935552 Type:vfs Inodes:3840000 HasInodes:true} {Device:/dev/sda1 Capacity:31158935552 Type:vfs Inodes:3840000 HasInodes:true}] DiskMap:map[8:0:{Name:sda Major:8 Minor:0 Size:32212254720 Scheduler:noop}] NetworkDevices:[{Name:ens4 MacAddress:42:01:0a:f0:00:39 Speed:-1 Mtu:1460}] Topology:[{Id:0 Memory:13656510464 Cores:[{Id:0 Threads:[0 1] Caches:[{Size:32768 Type:Data Level:1} {Size:32768 Type:Instruction Level:1} {Size:262144 Type:Unified Level:2}]}] Caches:[{Size:20971520 Type:Unified Level:3}]}] CloudProvider:GCE InstanceType:n1-highmem-2 InstanceID:8555047159068902293}
I0928 14:02:52.545440       1 manager.go:201] Version: {KernelVersion:4.4.0-34-generic ContainerOsVersion:Alpine Linux v3.4 DockerVersion:1.12.0 CadvisorVersion:v0.24.0 CadvisorRevision:0cdf491}
I0928 14:02:52.598527       1 factory.go:295] Registering Docker factory
W0928 14:02:52.598608       1 manager.go:244] Registration of the rkt container factory failed: unable to communicate with Rkt api service: rkt: cannot tcp Dial rkt api service: dial tcp [::1]:15441: getsockopt: connection refused
I0928 14:02:52.598631       1 factory.go:54] Registering systemd factory
I0928 14:02:52.598971       1 factory.go:86] Registering Raw factory
I0928 14:02:52.599374       1 manager.go:1082] Started watching for new ooms in manager
I0928 14:02:52.599635       1 oomparser.go:200] OOM parser using kernel log file: "/var/log/kern.log"
I0928 14:02:52.601033       1 manager.go:285] Starting recovery of all containers
I0928 14:02:53.262367       1 manager.go:290] Recovery completed
I0928 14:02:53.778738       1 cadvisor.go:157] Starting cAdvisor version: v0.24.0-0cdf491 on port 8080

```

The problem is I can't find any OOM events in cAdvisor. At the same time I'm using mtail to keep track of /var/log/kern.log file (OOM events are there). 

I tried to use API, without any result (/api/v1.3/events?oom_events=true&oom_kill_events=true).
I would appreciate any help :)

PK

### PR DESCRIPTION
**Pull request by euank**
My comment for PR https://github.com/kubernetes/node-problem-detector/pull/41#issue-189041129 applies here too.

This would fix https://github.com/kubernetes/kubernetes/issues/34965, probably fix #1484, and work-around/fix #645.

Things that should be considered before merging:

1) anywhere kubelet or cadvisor runs in a container now needs access to `/dev/kmsg`. This should be documented as a breaking change and various examples / docs might need changing.
2) this reduces a little how far back we can see (namely after the system reboots, we don't get things before that). This implies that a "kubelet crash -> container OOM -> node reboot" chain of events can lose that container OOM.
3) this works everywhere where the kernel is modern enough to run docker! Fewer dependencies!

Testing note: I removed the log-file formatted files. The parsing of log-files is now the responsibility of the kmsgparser package which lives elsewhere, so we can trust it to do the right thing. We also get to assume the timestamp etc.
I have not done manual testing of this change, but I have done decent manual testing of the kmsgparser.

### CODE REVIEW

File: utils/oomparser/oomparser.go [hunk 1]
```diff
@@ -101,132 +90,46 @@ func checkIfStartOfOomMessages(line string) bool {
...
-// At the end of an oom message group, StreamOoms adds the new oomInstance to
-// oomLog
-func (self *OomParser) StreamOoms(outStream chan *OomInstance) {
-	lineChannel := make(chan string, 10)
-	go func() {
-		readLinesFromFile(lineChannel, self.ioreader)
-	}()
+// StreamOoms writes to a provided a stream of OomInstance objects representing
+// OOM events that are found in the logs.
+// It will blocks and should be called from a goroutine.
```
Comment (timstclair) [inline utils/oomparser/oomparser.go]: nit: s/blocks/block/

File: utils/oomparser/oomparser.go [hunk 2]
```diff
@@ -101,132 +90,46 @@ func checkIfStartOfOomMessages(line string) bool {
...
-	}
-	tail, err := tail.NewTail(logFile)
-	if err != nil {
-		return nil, err
-	}
-	return &OomParser{
-		ioreader: bufio.NewReader(tail),
-	}, nil
+	// Should not happen
+	glog.Warningf("exiting analyzeLines. OOM events will not be reported.")
```
Comment (timstclair) [inline utils/oomparser/oomparser.go]: nit: If this really should not happen it should be error level

File: utils/oomparser/oomparser_test.go [hunk 3]
```diff
@@ -126,42 +118,203 @@ func TestCheckIfStartOfMessages(t *testing.T) {
...
+					"[ 1407]  1020  1407    25889      255      52        0             0 sshd",
+					"[ 1408]  1020  1408     5711      581      17        0             0 bash",
+					"[ 1425]     0  1425    25889      256      53        0             0 sshd",
+					"[ 1443]  1020  1443    25889      257      52        0             0 sshd",
+					"[ 1444]  1020  1444     5711      581      16        0             0 bash",
+					"[ 1476]  1020  1476     1809       25       9        0             0 tail",
+					"[ 1532]  1020  1532   410347   398810     788        0             0 badsysprogram",
+					"Out of memory: Kill process 1532 (badsysprogram) score 919 or sacrifice child",
+					"Killed process 1532 (badsysprogram) total-vm:1641388kB, anon-rss:1595164kB, file-rss:76kB",
+				},
```
Comment (timstclair) [inline utils/oomparser/oomparser_test.go]: Add a test case with multiple OOM events (note: I think writeAll needs to run in a goroutine to prevent deadlock)

File: utils/oomparser/oomparser.go [hunk 4]
```diff
@@ -101,132 +90,46 @@ func checkIfStartOfOomMessages(line string) bool {
...
 // initializes an OomParser object. Returns an OomParser object and an error.
 func New() (*OomParser, error) {
-	parser, err := trySystemd()
-	if err == nil {
-		return parser, nil
-	}
-	parser, err = tryLogFile()
-	if err == nil {
-		return parser, nil
+	parser, err := kmsgparser.NewParser()
```
Comment (timstclair) [inline utils/oomparser/oomparser.go]: nit: I like the logger pattern, consider setting the logger to use glog for consistency?

**Comment by timstclair** [comment]
Nice! This LGTM, but I'd like to get input from a few more people who understand the OOM pathways better than I do.

**Comment by timstclair** [comment]
@vishh - Could you take a look at this?

File: utils/oomparser/oomparser.go (hunk 2 above)
Comment (euank) [inline utils/oomparser/oomparser.go]: Before it was info and I thought it should be error, so I picked the middle as a compromise :innocent:

File: utils/oomparser/oomparser.go [hunk 5]
```diff
@@ -101,132 +90,46 @@ func checkIfStartOfOomMessages(line string) bool {
...
-func (self *OomParser) StreamOoms(outStream chan *OomInstance) {
-	lineChannel := make(chan string, 10)
-	go func() {
-		readLinesFromFile(lineChannel, self.ioreader)
-	}()
+// StreamOoms writes to a provided a stream of OomInstance objects representing
+// OOM events that are found in the logs.
+// It will blocks and should be called from a goroutine.
+func (self *OomParser) StreamOoms(outStream chan<- *OomInstance) {
+	kmsgEntries := self.parser.Parse()
```
Comment (euank) [inline utils/oomparser/oomparser.go]: Question: Should we call `self.parser.SeekEnd()` here or not?

I think `SeekEnd` more closely matches the `journalctl .. -f` behavior of before (start at the end of kmsg), but I think that looking a little into the past makes the kubelet behave more correctly after a restart.

Will OOM events that happen while the kubelet is down, but are detected on kubelet startup actually do the right thing?
Are they idempotent so that power-cycling the kubelet having bunches of duplicate events is okay?

Comment (timstclair) [inline utils/oomparser/oomparser.go]: I think reporting recent OOM events is desireable, and it's also consistent with the non-journald behavior.

File: utils/oomparser/oomparser_test.go (hunk 3 above)
Comment (euank) [inline utils/oomparser/oomparser_test.go]: Done

**Comment by euank** [comment]
@timstclair addressed your comments and fixed a bug where OOM events with a process name containing a `-` in them would break the parser (wouldn't match the end-line for that oom). Lucky me that my test program has a dash :smile:

**Comment by euank** [comment]
Rebased and squashed the commit addressing comments from back whenever.

**Comment by goettl79** [comment]
This fix  would also make the packaging issue of cadvisor / journalctl inside a docker container obsolete.  https://github.com/google/cadvisor/issues/1313

**Comment by euank** [comment]
Bump on this, did a rote rebase and afaict there aren't open concerns (other than waiting on whether @vishh feels like reviewing)

**Comment by euank** [comment]
@k8s-bot test this

**Comment by dchen1107** [comment]
cc/ @timstclair @dashpole @vishh

**Comment by euank** [comment]
Rebased for probably the 10th or so time.

Manually tested via the following:

```sh
$ ./cadvisor -v 3 -logtostderr
...
# cgroup OOM
$ docker run -m 15M euank/gunpowder-memhog:latest 30M
# cadvisor logs:
I0830 20:24:01.875221    3264 manager.go:1142] Created an OOM event in container "/docker/6da85dc9675db12149e970c6ef6835240bab712e5499963d13e88a446248e82b" at 2017-08-30 20:24:01.583571597 +0000 UTC

# system OOM
$ docker run -d euank/gunpowder-memhog 500M
$ sleep 5
$ echo f | sudo tee /proc/sysrq-trigger
# cadvisor logs
I0830 20:59:27.831699    1611 manager.go:1142] Created an OOM event in container "/" at 2017-08-30 20:59:27.717686391 +0000 UTC
```

@timstclair if this is going to land, can we land it?
Having to come by and rebase it once a month is ridiculous.

**Comment by vishh** [comment]
@euank I can help review this. is this ready for a review?

**Comment by euank** [comment]
@vishh yup, it's been ready for review for 9 months now.

**Comment by euank** [comment]
🎉
