### PR TITLE
Fix cAdvisor constantly polls data that has been disabled 

### LINKED ISSUE #2897: cAdvisor constantly polls data that has been disabled
Setup:
* Ubuntu 20.04 host (on Intel i9 CometLake)
* Few days old git head of runC & cAdvisor (and drm-tip kernel)

Use-case:
* Start cAdvisor so that all possible metrics have been disabled: `docker run -it --volume=/:/rootfs:ro --volume=/var/run:/var/run:ro --volume=/sys:/sys:ro --device=/dev/kmsg --publish=8080:8080 cadvisor:latest /usr/bin/cadvisor -disable_metrics accelerator,advtcp,cpuLoad,cpu_topology,cpuset,disk,diskIO,hugetlb,memory,memory_numa,network,oom_event,percpu,perf_event,process,referenced_memory,resctrl,sched,tcp,udp`
* Trace for 10s what files cAdvisor (at least tries to) open: `strace -f -e openat -p $(pidof cadvisor) 2> trace.txt`
* See what those files are

Expected output:
* None of the files for disabled metrics are queried

Actual output:
* cAdvisor constantly queries cpuset, hugetbl etc files:
```
$ cut -d'"' -f2 trace.txt | sed 's%^.*/%%' | sort | uniq -c | sort -nr
    191 memory.stat
    191 cpu.stat
    191 cpuset.sched_relax_domain_level
    191 cpuset.sched_load_balance
    191 cpuset.mems
    191 cpuset.memory_spread_slab
    191 cpuset.memory_spread_page
    191 cpuset.memory_pressure
    191 cpuset.memory_migrate
    191 cpuset.mem_hardwall
    191 cpuset.mem_exclusive
    191 cpuset.cpus
    191 cpuset.cpu_exclusive
    178 memory.use_hierarchy
    178 memory.usage_in_bytes
    178 memory.numa_stat
    178 memory.memsw.usage_in_bytes
    178 memory.memsw.max_usage_in_bytes
    178 memory.memsw.limit_in_bytes
    178 memory.memsw.failcnt
    178 memory.max_usage_in_bytes
    178 memory.limit_in_bytes
    178 memory.kmem.usage_in_bytes
    178 memory.kmem.tcp.usage_in_bytes
    178 memory.kmem.tcp.max_usage_in_bytes
    178 memory.kmem.tcp.limit_in_bytes
    178 memory.kmem.tcp.failcnt
    178 memory.kmem.max_usage_in_bytes
    178 memory.kmem.limit_in_bytes
    178 memory.kmem.failcnt
    178 memory.failcnt
    171 pids.max
    171 pids.current
    162 cpuacct.usage_percpu
    162 cpuacct.usage_all
    162 cpuacct.usage
    162 cpuacct.stat
     38 hugetlb.2MB.usage_in_bytes
     38 hugetlb.2MB.max_usage_in_bytes
     38 hugetlb.2MB.failcnt
```

### PR DESCRIPTION
**Pull request by Creatone**
Fixes #2897

### CODE REVIEW

File: build/integration.sh [hunk 1]
```diff
@@ -26,7 +26,7 @@ printf "" # Refresh sudo credentials if necessary.
 function start {
   set +e  # We want to handle errors if cAdvisor crashes.
   echo ">> starting cAdvisor locally"
-  GORACE="halt_on_error=1" ./cadvisor --docker_env_metadata_whitelist=TEST_VAR --v=6 --logtostderr $CADVISOR_ARGS &> "$log_file"
+  GORACE="halt_on_error=1" ./cadvisor --disable_metrics="memory_numa,tcp,udp,advtcp,sched,process,hugetlb,referenced_memory,cpu_topology,resctrl" --docker_env_metadata_whitelist=TEST_VAR --v=6 --logtostderr $CADVISOR_ARGS &> "$log_file"
```
Comment (eero-t) [inline build/integration.sh:29]: I think it would be good to have a comment above this telling which metrics should NOT be disabled.

Comment (Creatone) [reply build/integration.sh:30]: Good idea :+1:

File: build/integration.sh [hunk 2]
```diff
@@ -26,7 +26,8 @@ printf "" # Refresh sudo credentials if necessary.
 function start {
   set +e  # We want to handle errors if cAdvisor crashes.
   echo ">> starting cAdvisor locally"
-  GORACE="halt_on_error=1" ./cadvisor --docker_env_metadata_whitelist=TEST_VAR --v=6 --logtostderr $CADVISOR_ARGS &> "$log_file"
+  # This cpu, cpuset, percpu, app, memory, disk, diskIO, network, perf_event metrics should be enabled.
```
Comment (eero-t) [inline build/integration.sh:29]: This -> The ?

Btw.  If this PR would depend on PR#2902, it would be enough to change "disable_metrics" for "enable_metrics" option, to document what metrics the testing actually needs.

File: build/integration.sh [hunk 3]
```diff
@@ -26,7 +26,8 @@ printf "" # Refresh sudo credentials if necessary.
 function start {
   set +e  # We want to handle errors if cAdvisor crashes.
   echo ">> starting cAdvisor locally"
-  GORACE="halt_on_error=1" ./cadvisor --docker_env_metadata_whitelist=TEST_VAR --v=6 --logtostderr $CADVISOR_ARGS &> "$log_file"
+  # This cpuset, percpu, memory, disk, diskIO, network, perf_event metrics should be enabled.
```
Comment (eero-t) [inline build/integration.sh:29]: Now that -enable_metrics is used, this could say e.g. "enable only metrics required by the test", or be even removed.

Comment (Creatone) [reply build/integration.sh:29]: In my opinion, that comment is more accurate than `"enable only metrics required by the test"`.

Comment (eero-t) [reply build/integration.sh:29]: Comment metrics list just duplicates -enable_metrics argument, so it's redundant / can get out of sync later. Comment is a bit weirdly at the moment too ("This" -> "The"?).  But feel free to ignore my comment "bike-shedding", it's not really important, like rest of this PR.

**Comment by eero-t** [comment]
Btw.  Do integration tests need also "app" and "cpu" metrics?

Currently they are always enabled, as those two (are only ones that) are not in the ignoreWhitelist, but that is going to change with PR #2910.

**Comment by Creatone** [comment]
@bobbypage, @iwankgb, @dims, @mrunalp PTAL

**Comment by eero-t** [comment]
I tested this earlier, and verified that it fixes the #2897 issue I filed.

@Creatone  Now that you merged PR #2910 which made also app & cpu metrics optional, should those be added to the "-enable_metrics" option in integration.sh?

**Comment by bobbypage** [comment]
Thanks @Creatone for the fix. LGTM!

**Review by bobbypage — APPROVED** [review]
