### PR TITLE
Switch to Prometheus decoders for Prometheus custom metric endpoint parsing

### LINKED ISSUE #1472: Prometheus collector does not handle spaces in label values
The Prometheus metrics collector does not appear to handle spaces in the label values. For example, this metric:
```
my_metric{name="Network Agent"} 0
```

Will cause the following exception:
```
Failed to update stats for container "/docker/c039": Error 0: Error 0: strconv.ParseFloat: parsing "Agent\"} 0"
```

This is a valid label value according to the [Prometheus docs](https://prometheus.io/docs/concepts/data_model/): "Label values may contain any Unicode characters."

Problem seems to be that the parsing code treats the first space as the delimiter between the metric and its value, regardless of where it appears on the line: https://github.com/google/cadvisor/blob/552d2578ecc1d51118da5804bd19e832666b361d/collector/prometheus_collector.go#L188

### PR DESCRIPTION
**Pull request by jimmidyson**
Fixes #1472

@fabxc This is a hand-rolled parser to collect application metrics from containers. Forgetting the question or application metrics & cadvisor, I assume the better approach for this would be to use Prometheus' own parser? If so, can you point me to it please?

### CODE REVIEW

**Comment by jimmidyson** [comment]
`mkdir: cannot create directory ‘/tmp/cadvisor-768’: No space left on device` - @timstclair any chance you could sort that out?

**Comment by fabxc** [comment]
For reference, the parser is located in https://github.com/prometheus/common/tree/master/expfmt

**Comment by jimmidyson** [comment]
@fabxc Would be you be able to take a look if you have some time? Switched to expfmt decoders & seems to work nicely (few tweaks to tests but nothing fundamental changing in functionality).

**Comment by timstclair** [comment]
@jimmidyson I'm aware of the issue. I'll try to have it sorted out by EOD

**Comment by timstclair** [comment]
@k8s-bot test this

File: collector/prometheus_collector.go [hunk 1]
```diff
@@ -168,59 +170,54 @@ func (collector *PrometheusCollector) Collect(metrics map[string][]v1.MetricVal)
...
+				continue
 			}
 
 			metric := v1.MetricVal{
-				Label:      metLabel,
-				FloatValue: metVal,
-				Timestamp:  currentTime,
+				FloatValue: float64(sample.Value),
+				Timestamp:  sample.Timestamp.Time(),
 			}
```
Comment (fabxc) [inline collector/prometheus_collector.go]: Not sure I entirely understand this. We seem to ignore the labels of the samples entire and just append timestamp/value pairs for the metric name?

Comment (jimmidyson) [inline collector/prometheus_collector.go]: Ah yeah I forgot to ask what the purpose of this label was. Considering there are likely to be multiple labels on each metric, what should this be set to? @timstclair?

File: collector/prometheus_collector.go [hunk 2]
```diff
@@ -17,13 +17,14 @@ package collector
...
 	"fmt"
-	"io/ioutil"
-	"math"
+	"io"
 	"net/http"
-	"strconv"
-	"strings"
 	"time"
 
+	dto "github.com/prometheus/client_model/go"
```
Comment (timstclair) [inline collector/prometheus_collector.go]: what does `dto` stand for?

File: collector/prometheus_collector.go [hunk 3]
```diff
@@ -168,59 +170,54 @@ func (collector *PrometheusCollector) Collect(metrics map[string][]v1.MetricVal)
...
+		Dec: expfmt.NewDecoder(response.Body, expfmt.ResponseFormat(response.Header)),
+		Opts: &expfmt.DecodeOptions{
+			Timestamp: model.TimeFromUnixNano(currentTime.UnixNano()),
+		},
+	}
 
-	for _, line := range lines {
-		if line == "" {
+	var (
+		decSamples = make(model.Vector, 0, 50)
```
Comment (timstclair) [inline collector/prometheus_collector.go]: How'd you pick 50? What happens if this overflows?

Comment (fabxc) [inline collector/prometheus_collector.go]: It's just the initial capacity. The slice is appended to, so it just allocates more if we go beyond.
50 SGTM. It's a number of metrics we can expect from virtually any endpoint, grow allocations beyond that are fine. But we basically save 6 re-allocations for the general case.

File: collector/prometheus_collector.go (hunk 2 above)
Comment (fabxc) [inline collector/prometheus_collector.go]: Data transfer object. Kinda nasty, but better than `go` and kinda what we use everywhere else in Prometheus land.

File: collector/prometheus_collector.go (hunk 1 above)
Comment (jimmidyson) [inline collector/prometheus_collector.go]: @timstclair @DirectXMan12 What should the value of label be in this case? A concatenation of all Prometheus labels?

File: collector/prometheus_collector.go [hunk 4]
```diff
@@ -100,62 +101,63 @@ func (collector *PrometheusCollector) Name() string {
...
+// metricType converts Prometheus metric type to cadvisor metric type.
+// If there is no mapping then just return the name of the Prometheus metric type.
+func metricType(t dto.MetricType) v1.MetricType {
+	switch t {
+	case dto.MetricType_COUNTER:
+		return v1.MetricCumulative
+	case dto.MetricType_GAUGE:
+		return v1.MetricGauge
+	default:
+		return v1.MetricType(t.String())
```
Comment (DirectXMan12) [inline collector/prometheus_collector.go]: uhh..., if people are expecting this to be only one of these set values, this is going to throw them for a loop.
`v1.MetricType`  seems to be an implicit enumeration (since Go doesn't have explicit enumerations :-/), so I really don't think it's a good idea to arbitrarily add extra values to the enum at runtime.

File: collector/prometheus_collector.go [hunk 5]
```diff
@@ -100,62 +101,63 @@ func (collector *PrometheusCollector) Name() string {
...
+	for {
+		d := dto.MetricFamily{}
+		if err = dec.Decode(&d); err != nil {
+			break
+		}
+		name := d.GetName()
+		if len(name) == 0 {
+			continue
 		}
+		if _, ok := collector.metricsSet[name]; collector.metricsSet != nil && !ok {
```
Comment (DirectXMan12) [inline collector/prometheus_collector.go]: this could really use a comment to indicate why it's checking this (e.g. `// skip any metrics not on our list to collect`).  I realize that the old code doesn't have a comment, but we should fix that (I blame myself :-P).

File: collector/prometheus_collector.go (hunk 3 above)
Comment (DirectXMan12) [inline collector/prometheus_collector.go]: you should probably add a comment noting that it's just a guess at a useful initial capacity

File: collector/prometheus_collector.go (hunk 1 above)
Comment (DirectXMan12) [inline collector/prometheus_collector.go]: >  A concatenation of all Prometheus labels?

Yeah, seems like it.  That seems... poor.  It works *ok* for one label, but multiple labels could come in any order.  If we wanted to make sure this was comparable, we could sort them first.  Doesn't look like the label is actually carried through to the Kube summary API.

File: collector/prometheus_collector.go (hunk 2 above)
Comment (DirectXMan12) [inline collector/prometheus_collector.go]: none-the-less, something more expressive might be in order (perhaps `rawmodel` or `rawtypes`?)

File: collector/prometheus_collector.go (hunk 1 above)
Comment (timstclair) [inline collector/prometheus_collector.go]: Yeah, I agree this is not ideal. Unfortunately this requires an API change to fix properly. Can you file an issue? Sorting + concatenating sounds good for now. Check the allowed symbols on prometheus labels to decide how to concatenate.

Comment (fabxc) [inline collector/prometheus_collector.go]: In label values all unicode runes are allowed. In Prometheus itself we hance us `\0xff` as an invalid rune as a separator for unambiguous concatenation.

File: collector/prometheus_collector.go (hunk 2 above)
Comment (fabxc) [inline collector/prometheus_collector.go]: Agreed

File: collector/prometheus_collector.go (hunk 4 above)
Comment (jimmidyson) [inline collector/prometheus_collector.go]: Types aren't arbitrary, it's just that cadvisor doesn't support the same metric types as Prometheus & there's no way to map e.g. a Prometheus histogram to a cadvisor metric type.

File: collector/prometheus_collector.go (hunk 5 above)
Comment (jimmidyson) [inline collector/prometheus_collector.go]: Done.

File: collector/prometheus_collector.go (hunk 4 above)
Comment (jimmidyson) [inline collector/prometheus_collector.go]: Still not sure how to handle this nicely... This PR doesn't fix the existing problem, but doesn't make it worse so will raise a separate issue to figure out how to handle it, but assume that to be in a separate PR.

File: collector/prometheus_collector.go (hunk 3 above)
Comment (jimmidyson) [inline collector/prometheus_collector.go]: Done.

File: collector/prometheus_collector.go (hunk 2 above)
Comment (jimmidyson) [inline collector/prometheus_collector.go]: Done.

File: collector/prometheus_collector.go (hunk 1 above)
Comment (jimmidyson) [inline collector/prometheus_collector.go]: Hope what I've done it right... always confused by unicode stuff like this. Added tests too.

**Comment by jimmidyson** [comment]
Ready for a second round review.

**Comment by jimmidyson** [comment]
@timstclair What's left to get this merged?

**Comment by timstclair** [comment]
LGTM, feel free to merge.
