### PR TITLE
Fix race between `OnDemandHousekeeping` and `housekeepingTick`

### LINKED ISSUE #2754: Data race between `OnDemandHousekeeping` and `housekeepingTick`
`statsLastUpdatedTime` which is part of the `containerData` struct is read from  `OnDemandHousekeeping` and written to in `housekeepingTick`. These could be running under different go routines and so need to be guarded by the `containerData` lock.

### PR DESCRIPTION
**Pull request by pkagrawal**
This fixes the data race between the functions which could be running
in different goroutines.

Signed-off-by: Pradyumna Agrawal <pradyumnaa@vmware.com>

Fixes #2754

### CODE REVIEW

**Comment by pkagrawal** [comment]
Fixes #2754

File: manager/container.go [hunk 1]
```diff
@@ -555,6 +558,8 @@ func (cd *containerData) housekeepingTick(timer <-chan time.Time, longHousekeepi
 		klog.V(3).Infof("[%s] Housekeeping took %s", cd.info.Name, duration)
 	}
 	cd.notifyOnDemand()
+	cd.lock.Lock()
```
Comment (iwankgb) [inline manager/container.go:561]: I believe that call above this line is responsible for synchronization with `containerData.OnDemandHousekeeping()`. Lock that you are trying to introduce looks redundant to me. Are you able to provide a test case that help race to manifest?

Comment (pkagrawal) [reply manager/container.go:561]: I don't have a test case, but we were using cadvisor and our race detector tripped up:

```
WARNING: DATA RACE
Read at 0x00c0001e7a50 by goroutine 30:
  github.com/google/cadvisor/manager.(*containerData).OnDemandHousekeeping()
      vendor/github.com/google/cadvisor/manager/container.go:141 +0x9b
  github.com/google/cadvisor/manager.(*manager).getRequestedContainers.func1()
      vendor/github.com/google/cadvisor/manager/manager.go:741 +0x64

Previous write at 0x00c0001e7a50 by goroutine 130:
  github.com/google/cadvisor/manager.(*containerData).housekeepingTick()
      vendor/github.com/google/cadvisor/manager/container.go:558 +0x34c
  github.com/google/cadvisor/manager.(*containerData).housekeeping()
      vendor/github.com/google/cadvisor/manager/container.go:494 +0x304
```

Comment (iwankgb) [reply manager/container.go:561]: Thank you 🙇. I think we should use single synchronisation mechanism in this case. I wonder if moving notifyOnDemand() call a bit lower and applying similar change to OnDemandHousekeeping() would not solve the issue.

Comment (pkagrawal) [reply manager/container.go:561]: Thanks for looking. I'm not quite sure that I follow what you mean by single synchronization. `OnDemandHousekeeping` is an external API so anyone can call it, and it can potentially race with `housekeepingTick` when both try and access `statsLastUpdatedTime`. Access to this variable should be guarded by some mutual exclusion - right?

Comment (pkagrawal) [reply manager/container.go:561]: @iwankgb Can you take a look at this again? Thanks!

Comment (iwankgb) [reply manager/container.go:561]: @pkagrawal I don't think I will be able to look at this issue again before coming weekend.

**Comment by iwankgb** [comment]
@pkagrawal I was trying to replicate your problem and I simply can do this. I wrote following simple test:
```golang
func TestOnDemandHousekeepingRace(t *testing.T) {
	statsList := itest.GenerateRandomStats(1, 4, 1*time.Second)
	stats := statsList[0]

	//cd, mockHandler, _, fakeClock := newTestContainerData(t)
	cd, mockHandler, _, _ := newTestContainerData(t)
	mockHandler.On("GetStats").Return(stats, nil)

	wg := sync.WaitGroup{}
	wg.Add(1)

	err := cd.Start()
	assert.NoError(t, err)

	go func() {
		t.Log("starting on demand goroutine")
		for i := 0; i < 100000; i++  {
			t.Logf("on demand iteration %d", i)
			cd.OnDemandHousekeeping(0 * time.Second)
		}
		wg.Done()
	}()
	wg.Wait()
}
```
and I can't get any race:
```
=== RUN   TestOnDemandHousekeepingRace
--- PASS: TestOnDemandHousekeepingRace (0.14s)
PASS
ok  	github.com/google/cadvisor/manager	1.260s
```

**Comment by iwankgb** [comment]
@pkagrawal I have just realized that I was trying to use race detector on `linux/arm64` and:
>          -race
>                enable data race detection.
>                Supported only on linux/amd64, freebsd/amd64, darwin/amd64 and windows/amd64.

Let me take one more look at this problem.

**Comment by iwankgb** [comment]
I do confirm that this is a real issue:
```
[root@fedora-s-4vcpu-8gb-fra1-01 cadvisor]# uname -m
x86_64
[root@fedora-s-4vcpu-8gb-fra1-01 cadvisor]# GOMAXPROCS=4 go test -v -race -run TestOnDemandHousekeepingRace ./manager/
=== RUN   TestOnDemandHousekeepingRace
    container_test.go:342: starting on demand goroutine
==================
WARNING: DATA RACE
Read at 0x00c0004c6610 by goroutine 108:
  github.com/google/cadvisor/manager.(*containerData).OnDemandHousekeeping()
      /root/go/src/github.com/google/cadvisor/manager/container.go:141 +0x9b
  github.com/google/cadvisor/manager.TestOnDemandHousekeepingRace.func2.1()
      /root/go/src/github.com/google/cadvisor/manager/container_test.go:346 +0x4e

Previous write at 0x00c0004c6610 by goroutine 100:
  github.com/google/cadvisor/manager.(*containerData).housekeepingTick()
      /root/go/src/github.com/google/cadvisor/manager/container.go:558 +0x34c
  github.com/google/cadvisor/manager.(*containerData).housekeeping()
      /root/go/src/github.com/google/cadvisor/manager/container.go:494 +0x304

Goroutine 108 (running) created at:
  github.com/google/cadvisor/manager.TestOnDemandHousekeepingRace.func2()
      /root/go/src/github.com/google/cadvisor/manager/container_test.go:344 +0xaf

Goroutine 100 (running) created at:
  github.com/google/cadvisor/manager.(*containerData).Start()
      /root/go/src/github.com/google/cadvisor/manager/container.go:114 +0x4c
  github.com/google/cadvisor/manager.TestOnDemandHousekeepingRace.func1()
      /root/go/src/github.com/google/cadvisor/manager/container_test.go:336 +0x49
==================
    testing.go:1038: race detected during execution of test
--- FAIL: TestOnDemandHousekeepingRace (0.06s)
=== CONT
    testing.go:1038: race detected during execution of test
FAIL
FAIL	github.com/google/cadvisor/manager	0.119s
FAIL
```
using following test case:
```golang
func TestOnDemandHousekeepingRace(t *testing.T) {
	statsList := itest.GenerateRandomStats(1, 4, 1*time.Second)
	stats := statsList[0]

	//cd, mockHandler, _, fakeClock := newTestContainerData(t)
	cd, mockHandler, _, _ := newTestContainerData(t)
	mockHandler.On("GetStats").Return(stats, nil)

	wg := sync.WaitGroup{}
	wg.Add(1002)

	go func() {
		time.Sleep(10 * time.Millisecond)
		err := cd.Start()
		assert.NoError(t, err)
		wg.Done()
	}()

	go func() {
		t.Log("starting on demand goroutine")
		for i := 0; i < 1000; i++  {
			go func() {
				time.Sleep(1 * time.Microsecond)
				cd.OnDemandHousekeeping(0 * time.Millisecond)
				wg.Done()
			}()
		}
		wg.Done()
	}()
	wg.Wait()
}
```

**Comment by iwankgb** [comment]
@pkagrawal, could you do the following:
* add "Fixes #2754" to PR description (otherwise the issue will not be linked)
* add a test case to prevent regression (you can use code that I pasted above)

I'm sorry for delaying you work but I had no idea that race detector works on amd64 **only**.

**Comment by iwankgb** [comment]
@bobbypage, I summon you as this is a bug indeed.

**Comment by pkagrawal** [comment]
@iwankgb Thanks for taking a look again and pointing me to a test case. I've now added your test case as well.
Also, I did comment "fixes #2754" here: https://github.com/google/cadvisor/pull/2755#issuecomment-740088944
Is that comment sufficient to link the issue and the PR?

**Comment by iwankgb** [comment]
LGTM

**Comment by bobbypage** [comment]
LGTM, thanks.

**Review by bobbypage — APPROVED** [review]
